import createClient from "openapi-fetch";
import type { paths } from "../generated/api-schema";

/**
 * Type-safe HTTP client for the FinRisk API.
 * Uses paths generated by openapi-typescript; transport is openapi-fetch.
 *
 * In dev, leave `VITE_API_BASE_URL` unset so requests go to the Vite dev
 * server and are proxied to the Java API (see vite.config.ts).
 */
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? "";

export const apiClient = createClient<paths>({ baseUrl });
