import createClient from "openapi-fetch";
import type { paths } from "../generated/api-schema";

/**
 * Type-safe HTTP client for the FinRisk API.
 * Uses paths generated by openapi-typescript; transport is openapi-fetch.
 *
 * In dev, keep `VITE_API_BASE_URL` unset: the browser calls same-origin `/api/...`
 * and Vite proxies to the Docker API on port 18080 (see vite.config.ts).
 * For preview/production without a proxy, set `VITE_API_BASE_URL` to the API origin.
 */
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? "";

export const apiClient = createClient<paths>({ baseUrl });
