/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1b1b",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed-variant": "#812800",
        background: "#fcf9f8",
        "on-error-container": "#93000a",
        "surface-bright": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        outline: "#76777d",
        "on-surface-variant": "#45464d",
        "error-container": "#ffdad6",
        tertiary: "#000000",
        "primary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#00201a",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#005145",
        surface: "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#007261",
        "surface-variant": "#e5e2e1",
        "primary-fixed": "#dae2fd",
        "secondary-container": "#68fadd",
        "secondary-fixed-dim": "#44ddc1",
        "on-surface": "#1c1b1b",
        error: "#ba1a1a",
        "surface-tint": "#565e74",
        "tertiary-container": "#380d00",
        "on-tertiary-container": "#e94f00",
        "surface-container-high": "#eae7e7",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#68fadd",
        "on-tertiary-fixed": "#380d00",
        "primary-container": "#131b2e",
        "tertiary-fixed": "#ffdbcf",
        "inverse-primary": "#bec6e0",
        "surface-dim": "#dcd9d9",
        "inverse-on-surface": "#f3f0ef",
        "surface-container": "#f0eded",
        "inverse-surface": "#313030",
        primary: "#000000",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#ffb59b",
        secondary: "#006b5c",
        "on-error": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      spacing: {
        "margin-desktop": "32px",
        unit: "4px",
        "card-padding": "20px",
        gutter: "16px",
        "section-gap": "40px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "data-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      keyframes: {
        "dashboard-calc-reveal": {
          from: { opacity: "0", transform: "translateY(-8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "dashboard-calc-reveal": "dashboard-calc-reveal 0.45s ease-out both",
      },
    },
  },
  plugins: [],
};
